name: Deploy Vercel
description: Deploy Vercel in two modes

inputs:
  vercel-token:
    description: 'Vercel token'
    required: true
  mode:
    description: 'Deployment mode'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Vercel CLI
      run: npm install --global vercel@canary
      shell: bash

    - name: PRODUCTION Vercel Deployment
      if: ${{ inputs.mode == 'production' }}
      run: |
        vercel pull --yes --environment=production --token=${{ inputs.vercel-token }}
        vercel build --prod --token=${{ inputs.vercel-token }}
        vercel deploy --prebuilt --prod --token=${{ inputs.vercel-token }}
      shell: bash

    - name: PREVIEW Vercel Deployment
      if: ${{ inputs.mode == 'preview' }}
      run: |
        vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }}
        vercel build --token=${{ inputs.vercel-token }} --env DATABASE_URL=${{ secrets.DATABASE_URL }} --env NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} --env NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
        vercel deploy --prebuilt --token=${{ inputs.vercel-token }} --env DATABASE_URL=${{ secrets.DATABASE_URL }} --env NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} --env NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
      shell: bash
